# Generated by Django 5.0.1 on 2024-02-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
